### ISSUE TITLE
Add button to reject all cookies

### ISSUE THREAD

**Issue by thomfre** [bouvet-apps/app-cookie-panel#4]
Add button to let the user reject all cookies without having to navigate away from the initial page of the cookie panel. If possible let the user reject **all** cookies, if some cookies really are required (not just because you want them there), let the user know so by naming the button "Reject all non-essential" or similar.

**Comment by dholmen** [comment]
Having an extra button will probably clutter the interface a bit too much (especially on mobile devices), so I would suggest changing the "Adjust cookie settings" button to a link.

**Comment by thomfre** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/10846906/122916799-9202ac00-d35d-11eb-97ae-dcef32d5e8e1.png)

**Comment by tazhel** [comment]
Just wanted to mention that you should not be navigated away from the page. You click Tilpass -> lagre og lukk.
So it is just one extra click to reject them all.

**Comment by matsovevada** [comment]
This was fixed with #6, so i'm closing this issue
